"""12/02/2026 9h44

Revision ID: 39850c6b43fd
Revises: 14461f81385e
Create Date: 2026-02-12 09:44:54.487659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39850c6b43fd'
down_revision = '14461f81385e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biography', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('biography')

    # ### end Alembic commands ###
