"""10/02/2026 11h33

Revision ID: b4a7bbacd377
Revises: 9caa7175638e
Create Date: 2026-02-10 23:33:42.900361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a7bbacd377'
down_revision = '9caa7175638e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('session_duration')

    # ### end Alembic commands ###
